function alpha_ddot = dinamica_alpha_live(u, mm, mc, cm, cc, L, g)
    % u = [ alpha_dot, alpha, xc_dot, xc, Fc]
    alpha_dot = u(1);
    alpha = u(2);
    xc_dot = u(3);
    xc = u(4);
    Fc = u(5);

    % alpha_ddot = ...;
    alpha_ddot = (mc * cm * sin(alpha) * xc_dot ...
                    - mm * sin(alpha) * cc * xc_dot ...
                    + mm^2 * L * sin(alpha) * cos(alpha) * alpha_dot^2  ...
                    + mm * sin(alpha) * Fc ...
                    + mm^2 * g * cos(alpha) ...
                    + mm * mc * g * cos(alpha) ...
                    - mc * cm * L * alpha_dot ...
                    - mm * cm * L * (cos(alpha))^2 * alpha_dot ...
                   ) / ((mm * cos(alpha)^2 + mc) * mm * L);
end